In [9]:
import cv2
img = cv2.imread("House.png")
print(img)
print(len(img))
print(img.shape)
# img = img.reshape()

[[[167 144 128]
  [171 143 126]
  [178 149 134]
  ...
  [145 158 172]
  [143 164 172]
  [143 159 171]]

 [[167 144 128]
  [171 145 129]
  [175 149 133]
  ...
  [152 163 177]
  [147 163 175]
  [152 164 176]]

 [[172 147 131]
  [169 143 129]
  [166 140 126]
  ...
  [148 157 171]
  [146 158 170]
  [139 156 169]]

 ...

 [[140 154 166]
  [150 155 170]
  [152 159 174]
  ...
  [ 73  71  83]
  [ 83  76  83]
  [ 80  82  82]]

 [[136 149 163]
  [143 156 170]
  [148 159 173]
  ...
  [ 50  53  68]
  [ 65  64  74]
  [ 80  82  83]]

 [[137 153 169]
  [139 158 171]
  [143 159 172]
  ...
  [ 71  76  75]
  [ 55  63  63]
  [ 59  62  66]]]
628
(628, 964, 3)
