In [1]:

import cv2
import numpy

In [3]:
print(numpy.ones(3))
print(numpy.zeros(4))
print(numpy.array([[1,3],[3,4]]) - 1)
print(numpy.ones((3,4)))
print(numpy.array([[1,3],[3,4]])*numpy.array([[1,3],[3,4]]))

[1. 1. 1.]
[0. 0. 0. 0.]
[[0 2]
 [2 3]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1  9]
 [ 9 16]]
